author: Jackson Goerner
difficulty: 800
export_config:
  mcpc-problems:
    location: ~/Desktop/problemtools
    problemtools_config: {}
    type: problemtools
limits:
  memory: 262144
  time: 1
name: Maximum of a List
state: in-progress
tags:
- implementation
type: standard
