name: Maximum of a List
type: standard
tags:
  - implementation
difficulty: 800
export_config:
  mcpc-problems:
    type: problemtools
    location: ~/Desktop/problemtools
    problemtools_config: {}
state: in-progress
limits:
  time: 1
  memory: 262144
author: Jackson Goerner
